select * from EMPLOYEES where JOB_ID in (select JOB_IDENT from JOBS);
select * from EMPLOYEES;
select * from JOBS;

select * from JOBS where JOB_IDENT in (select JOB_ID from EMPLOYEES where SALARY > 70000);

select * 
from EMPLOYEES, JOBS
where EMPLOYEES.JOB_ID = JOBS.JOB_IDENT;

select *
	from EMPLOYEES E, JOBS J
    where E.JOB_ID = J.JOB_IDENT;

select EMP_ID, F_NAME, L_NAME, JOB_TITLE
	from EMPLOYEES E, JOBS J
    where  E.JOB_ID = J.JOB_IDENT;
    
SELECT E.EMP_ID, E.F_NAME, E.L_NAME, J.JOB_TITLE
FROM EMPLOYEES E, JOBS J 
WHERE E.JOB_ID = J.JOB_IDENT;

SELECT E.EMP_ID, E.F_NAME, E.L_NAME, J.JOB_TITLE
FROM EMPLOYEES E, JOBS J 
WHERE E.JOB_ID IN (SELECT JOB_IDENT FROM JOBS WHERE JOB_TITLE = "Jr. Designer");

#ESTA MAL PORQUE NO ESTOY UNIENDO BIEN LAS TABLAS 
SELECT EMPLOYEES.EMP_ID, EMPLOYEES.F_NAME, EMPLOYEES.L_NAME, JOBS.JOB_TITLE
FROM EMPLOYEES, JOBS
WHERE JOBS.JOB_IDENT in (SELECT JOB_IDENT FROM JOBS WHERE JOB_TITLE = "Jr. Designer");

SELECT JOB_ID FROM EMPLOYEES;
SELECT JOB_IDENT FROM JOBS WHERE JOB_TITLE = "Jr. Designer";

SELECT *
FROM EMPLOYEES E
WHERE JOB_ID IN (SELECT JOB_IDENT
				 FROM JOBS 
                 WHERE JOB_TITLE = "Jr. Designer");

SELECT   E.EMP_ID, E.F_NAME, E.L_NAME, J.JOB_TITLE 
 FROM EMPLOYEES E, JOBS J
 WHERE E.JOB_ID = J.JOB_IDENT AND J.JOB_TITLE = "Jr. Designer";
 
 # SE HACE CORECTA PORQUE DATE ESTA DADA EN 10 DIGITOS 
 SELECT *
 FROM JOBS
 WHERE JOB_IDENT IN (SELECT JOB_ID FROM EMPLOYEES WHERE B_DATE >= 19770000);
 
SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, JOB_IDENT
FROM JOBS
WHERE JOB_IDENT IN (SELECT JOB_ID
                    FROM EMPLOYEES
                    WHERE YEAR(B_DATE)>1976 );
                    
SELECT *
FROM JOBS J, EMPLOYEES E
WHERE E.JOB_ID = JOB_IDENT AND E.B_DATE > 19770000; 